class Commands:
    LEECH = "leech@apaleechbot"
    PURGE = "purge@apaleechbot"
    PAUSEALL = "pauseall@apaleechbot"
    RESUMEALL = "resumeall@apaleechbot"
    STATUS = "status@apaleechbot"
    SETTINGS = "settings@apaleechbot"
    EXEC = "exec@apaleechbot"
    UPLOAD = "upload@apaleechbot"
    YTDL = "ytdl@apaleechbot"
    PYTDL = "pytdl@apaleechbot"
    ABOUT = "about@apaleechbot"
    GETLOGS = "getlogs@apaleechbot"
    SERVER = "server@apaleechbot"
    USERSETTINGS = "usetting@apaleechbot"
    INSTADL = "instadl@apaleechbot"
